export const ROUTES = {
    ROOT: '/',
    HOME: "/home",
    LOGIN: "/login",
    MY_ACCOUNT: "/my-account",
    ADD_TRAINER: "add-trainer",
    TRAINING: "trainings",
    ADD_TRAINING: "add-training",
    CHANGE_PASSWORD: "change-password",
    JOIN_US: "/join-us",
    REGISTRATION: "/registration",
    SUCCESS: 'success',
    BLOG: "/blog",
    PRICING: "/pricing",
    FEATURES: "/features",
    ABOUT_US: "/about-us",
    CONTACT_US: "/contact-us",
    USER_GUIDES: "/user-guides",
    WEBINARS: "/webinars",
    PRIVACY: "/privacy",
    TERMS: "/terms",
    NOT_FOUND: '/not-found',
};
